# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_product_tap_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_taps', models.IntegerField(default=0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Product')),
                ('user', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
