# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tap',
            name='total_taps',
        ),
        migrations.AddField(
            model_name='product',
            name='taps',
            field=models.IntegerField(default=0),
        ),
    ]
