# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-01 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20170201_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tap',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='tap',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='trashes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Tap',
        ),
    ]
